env:
  browser: true
  es2022: true
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:unicorn/recommended
  - prettier
parser: '@typescript-eslint/parser'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.json
plugins:
  - '@typescript-eslint'
  - unicorn
rules:
  unicorn/prefer-top-level-await: off
